
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class ButtonsPanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    boolean isMax = true;

    /**
     * Creates new form ButtonsPanel
     */
    public ButtonsPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        setThemeIcon(mainFrame.isDark);
    }

    public void setThemeIcon(boolean isDark) {
        String iconName = isDark ? "setting-dark.png" : "setting-light.png";
        Image img = new ImageIcon(getClass().getResource("/resources/" + iconName)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(img));

        String menuIconName = isDark ? "menu-dark-max.png" : "menu-light-max.png";
        Image menuImg = new ImageIcon(getClass().getResource("/resources/" + menuIconName)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        jLabel2.setText("");
        jLabel2.setIcon(new ImageIcon(menuImg));

        String dashboardIcon = isDark ? "dashboardIcon-for-dark.png" : "dashboardIcon-for-light.png";
        dashboardButton.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/resources/" + dashboardIcon)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        String addEmployeeIcon = isDark ? "addEmployeeIcon-for-dark.png" : "addEmployeeIcon-for-light.png";
        addEmployeeButton.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/resources/" + addEmployeeIcon)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        String employeeListIcon = isDark ? "employeeListIcon-for-dark.png" : "employeeListIcon-for-light.png";
        viewEmployeesButton.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/resources/" + employeeListIcon)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));

        String attendaceListIcon = isDark ? "attendanceListIcon-for-dark.png" : "attendanceListIcon-for-light.png";
        attendanceListButton.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/resources/" + attendaceListIcon)).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        northPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        gridPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        addEmployeeButton = new javax.swing.JButton();
        viewEmployeesButton = new javax.swing.JButton();
        attendanceListButton = new javax.swing.JButton();
        southPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        setMaximumSize(new java.awt.Dimension(220, 0));
        setMinimumSize(new java.awt.Dimension(50, 0));
        setPreferredSize(new java.awt.Dimension(220, 0));
        setLayout(new java.awt.BorderLayout());

        northPanel.setPreferredSize(new java.awt.Dimension(220, 50));
        northPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".....");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        northPanel.add(jLabel2);

        add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.GridBagLayout());

        gridPanel.setOpaque(false);
        gridPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        dashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardButton.setText("DASHBOARD");
        dashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardButton.setFocusable(false);
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dashboardButton.setMaximumSize(new java.awt.Dimension(200, 40));
        dashboardButton.setMinimumSize(new java.awt.Dimension(40, 40));
        dashboardButton.setPreferredSize(new java.awt.Dimension(200, 40));
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        gridPanel.add(dashboardButton);

        addEmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmployeeButton.setText("ADD EMPLOYEE");
        addEmployeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeeButton.setFocusable(false);
        addEmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addEmployeeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addEmployeeButton.setMaximumSize(new java.awt.Dimension(200, 40));
        addEmployeeButton.setMinimumSize(new java.awt.Dimension(40, 40));
        addEmployeeButton.setPreferredSize(new java.awt.Dimension(200, 40));
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });
        gridPanel.add(addEmployeeButton);

        viewEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewEmployeesButton.setText("VIEW EMPLOYEES");
        viewEmployeesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewEmployeesButton.setFocusable(false);
        viewEmployeesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEmployeesButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewEmployeesButton.setMaximumSize(new java.awt.Dimension(200, 40));
        viewEmployeesButton.setMinimumSize(new java.awt.Dimension(40, 40));
        viewEmployeesButton.setPreferredSize(new java.awt.Dimension(200, 40));
        viewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesButtonActionPerformed(evt);
            }
        });
        gridPanel.add(viewEmployeesButton);

        attendanceListButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        attendanceListButton.setText("ATTENDANCE LIST");
        attendanceListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceListButton.setFocusable(false);
        attendanceListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        attendanceListButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        attendanceListButton.setMaximumSize(new java.awt.Dimension(200, 40));
        attendanceListButton.setMinimumSize(new java.awt.Dimension(40, 40));
        attendanceListButton.setPreferredSize(new java.awt.Dimension(200, 40));
        attendanceListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceListButtonActionPerformed(evt);
            }
        });
        gridPanel.add(attendanceListButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        centerPanel.add(gridPanel, gridBagConstraints);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        southPanel.setPreferredSize(new java.awt.Dimension(220, 50));
        southPanel.setLayout(new java.awt.GridBagLayout());

        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.setMaximumSize(new java.awt.Dimension(110, 40));
        logoutButton.setMinimumSize(new java.awt.Dimension(0, 0));
        logoutButton.setPreferredSize(new java.awt.Dimension(110, 40));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        southPanel.add(logoutButton, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".....");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);
        jLabel1.setMaximumSize(new java.awt.Dimension(35, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(35, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(35, 35));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        southPanel.add(jLabel1, gridBagConstraints);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        mainFrame.switchPanel(new DashboardPanel(mainFrame), "Dashboard");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        mainFrame.switchPanel(new AddEmployeePanel(mainFrame), "AddEmployee");
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void viewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesButtonActionPerformed
        mainFrame.switchPanel(new ViewEmployeesPanel(mainFrame), "ViewEmployees");
    }//GEN-LAST:event_viewEmployeesButtonActionPerformed

    private void attendanceListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceListButtonActionPerformed
        mainFrame.switchPanel(new AttendanceListPanel(mainFrame), "AttendanceList");
    }//GEN-LAST:event_attendanceListButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        if (JOptionPane.showConfirmDialog(mainFrame, "Are you sure you want to Logout?",
                "Confimation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            mainFrame.remove(mainFrame.buttonsPanel);
            mainFrame.switchPanel(new LoginPanel(mainFrame), "Login");

        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        mainFrame.remove(mainFrame.buttonsPanel);
        mainFrame.switchPanel(new SettingsPanel(mainFrame), "Settings");

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (isMax) {
            isMax = false;
            this.setPreferredSize(new java.awt.Dimension(50, 0));
            dashboardButton.setText("");
            addEmployeeButton.setText("");
            viewEmployeesButton.setText("");
            attendanceListButton.setText("");
        } else {
            isMax = true;
            this.setPreferredSize(new java.awt.Dimension(220, 0));
            dashboardButton.setText("DASHBOARD");
            addEmployeeButton.setText("ADD EMPLOYEE");
            viewEmployeesButton.setText("VIEW EMPLOYEES");
            attendanceListButton.setText("ATTENDANCE LIST");
        }

        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addEmployeeButton;
    public javax.swing.JButton attendanceListButton;
    private javax.swing.JPanel centerPanel;
    public javax.swing.JButton dashboardButton;
    private javax.swing.JPanel gridPanel;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton logoutButton;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southPanel;
    public javax.swing.JButton viewEmployeesButton;
    // End of variables declaration//GEN-END:variables
}
