
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class DashboardPanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        Count();
    }

    private void Count() {
        mainFrame.Connect();
        try {
            Statement stmt = mainFrame.connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) AS total_employees FROM employees_table");
            if (rs.next()) {
                totalEmployeesLabel.setText(String.valueOf(rs.getInt("total_employees")));
            }

            rs = stmt.executeQuery("SELECT COUNT(*) AS total_users FROM users_table");
            if (rs.next()) {
                totalUsersLabel.setText(String.valueOf(rs.getInt("total_users")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DashboardPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Counting Total Employee Failed! \n" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dashboardLabel = new javax.swing.JLabel();
        totalEmployeesPanel = new javax.swing.JPanel();
        employeesLabel = new javax.swing.JLabel();
        totalEmployeesLabel = new javax.swing.JLabel();
        totalUsersPanel = new javax.swing.JPanel();
        usersLabel = new javax.swing.JLabel();
        totalUsersLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.GridBagLayout());

        dashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        dashboardLabel.setText("DASHBOARD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 50, 10);
        add(dashboardLabel, gridBagConstraints);

        totalEmployeesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalEmployeesPanel.setOpaque(false);
        totalEmployeesPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        totalEmployeesPanel.setLayout(new java.awt.GridBagLayout());

        employeesLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        employeesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeesLabel.setText("EMPLOYEES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        totalEmployeesPanel.add(employeesLabel, gridBagConstraints);

        totalEmployeesLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalEmployeesLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        totalEmployeesPanel.add(totalEmployeesLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(totalEmployeesPanel, gridBagConstraints);

        totalUsersPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalUsersPanel.setOpaque(false);
        totalUsersPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        totalUsersPanel.setLayout(new java.awt.GridBagLayout());

        usersLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usersLabel.setText("USERS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        totalUsersPanel.add(usersLabel, gridBagConstraints);

        totalUsersLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalUsersLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        totalUsersPanel.add(totalUsersLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(totalUsersPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel employeesLabel;
    private javax.swing.JLabel totalEmployeesLabel;
    private javax.swing.JPanel totalEmployeesPanel;
    private javax.swing.JLabel totalUsersLabel;
    private javax.swing.JPanel totalUsersPanel;
    private javax.swing.JLabel usersLabel;
    // End of variables declaration//GEN-END:variables
}
