
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class LoginPanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        javax.swing.SwingUtilities.invokeLater(() -> usernameField.requestFocusInWindow());

        usernameField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    loginButtonActionPerformed(null); // Call the login action
                }
            }
        });

        passwordField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    loginButtonActionPerformed(null); // Call the login action
                }
            }
        });

        String savedUser = mainFrame.prefs.get("rememberedUser", null);
        if (savedUser != null) {
            try {
                PreparedStatement pstmt = mainFrame.connection.prepareStatement("SELECT * FROM users_table WHERE username = ?");
                pstmt.setString(1, savedUser);

                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    usernameField.setText(savedUser);
                    passwordField.setText(rs.getString("password"));
                    rememberMe.setSelected(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Fetching Failed!\n" + ex.getLocalizedMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centerPanel = new javax.swing.JPanel();
        loginFormPanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginHeaderLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        rememberMe = new javax.swing.JCheckBox();
        showPassword = new javax.swing.JCheckBox();
        designPanel = new javax.swing.JPanel();
        timeInOutButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.GridBagLayout());

        centerPanel.setBackground(new java.awt.Color(51, 51, 51));
        centerPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        centerPanel.setOpaque(false);
        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        centerPanel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        loginFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        loginFormPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        loginFormPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        loginFormPanel.setLayout(new java.awt.GridBagLayout());

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setMinimumSize(new java.awt.Dimension(250, 35));
        usernameField.setPreferredSize(new java.awt.Dimension(300, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        loginFormPanel.add(usernameField, gridBagConstraints);

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setMinimumSize(new java.awt.Dimension(250, 35));
        passwordField.setPreferredSize(new java.awt.Dimension(300, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        loginFormPanel.add(passwordField, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel.setText("USERNAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        loginFormPanel.add(usernameLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        loginFormPanel.add(passwordLabel, gridBagConstraints);

        loginHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        loginHeaderLabel.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginHeaderLabel, gridBagConstraints);

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeLabel.setText("WELCOME!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(welcomeLabel, gridBagConstraints);

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.setFocusable(false);
        loginButton.setOpaque(true);
        loginButton.setPreferredSize(new java.awt.Dimension(100, 35));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        loginFormPanel.add(loginButton, gridBagConstraints);

        rememberMe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rememberMe.setText("Remember Me");
        rememberMe.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        loginFormPanel.add(rememberMe, gridBagConstraints);

        showPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showPassword.setText("Show Password");
        showPassword.setFocusable(false);
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        loginFormPanel.add(showPassword, gridBagConstraints);

        centerPanel.add(loginFormPanel);

        designPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        designPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        designPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        designPanel.setLayout(new java.awt.GridBagLayout());

        timeInOutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeInOutButton.setText("TIME IN/TIME OUT");
        timeInOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeInOutButton.setFocusPainted(false);
        timeInOutButton.setFocusable(false);
        timeInOutButton.setMaximumSize(new java.awt.Dimension(200, 35));
        timeInOutButton.setMinimumSize(new java.awt.Dimension(200, 35));
        timeInOutButton.setOpaque(true);
        timeInOutButton.setPreferredSize(new java.awt.Dimension(200, 35));
        timeInOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInOutButtonActionPerformed(evt);
            }
        });
        designPanel.add(timeInOutButton, new java.awt.GridBagConstraints());

        centerPanel.add(designPanel);

        add(centerPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String user = usernameField.getText();
        String pwd = new String(passwordField.getPassword());
        if (user.isEmpty() || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username or Password Field is Empty!");
        } else {
            try {
                PreparedStatement pstmt = mainFrame.connection.prepareStatement("SELECT * FROM users_table WHERE username = ? AND password = ?");
                pstmt.setString(1, user);
                pstmt.setString(2, pwd);
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    if (rememberMe.isSelected()) {
                        mainFrame.prefs.put("rememberedUser", rs.getString("username"));
                    } else {
                        mainFrame.prefs.remove("rememberedUser");
                    }

                    usernameField.setText("");
                    passwordField.setText("");

                    mainFrame.switchPanel(new DashboardPanel(mainFrame), "Dashboard");

                    mainFrame.buttonsPanel = new ButtonsPanel(mainFrame);
                    mainFrame.add(mainFrame.buttonsPanel, java.awt.BorderLayout.WEST);

                } else {
                    mainFrame.cardLayout.show(mainFrame.mainPanel, "Login Panel");
                    JOptionPane.showMessageDialog(this, "Username or Password is Incorrect!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Login Failed!\n" + ex.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void timeInOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInOutButtonActionPerformed

        usernameField.setText("");
        passwordField.setText("");

        mainFrame.switchPanel(new TimeInOutPanel(mainFrame), "TimeInOut Panel");

//        new TimeInOutFrame(mainFrame).setVisible(true);

    }//GEN-LAST:event_timeInOutButtonActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            passwordField.setEchoChar((char) 0);
        } else {
            passwordField.setEchoChar('•');
        }
    }//GEN-LAST:event_showPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel designPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JLabel loginHeaderLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox rememberMe;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton timeInOutButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
