
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.CardLayout;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    Connection connection;

    CardLayout cardLayout;

    ButtonsPanel buttonsPanel;

    Preferences prefs = Preferences.userRoot().node("EmployeeManagementSystem.Preferences");
    boolean isDark = prefs.getBoolean("darkMode", false);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTheme(isDark);
        Connect();

        cardLayout = (CardLayout) (mainPanel.getLayout());

        LoginPanel loginPanel = new LoginPanel(this);
        switchPanel(loginPanel, "Login");

    }

    public void setTheme(boolean isDark) {
        try {
            if (isDark) {
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
            } else {
                UIManager.setLookAndFeel(new FlatMacLightLaf());
            }
            String iconName = isDark ? "employeeManagementIcon-for-dark.png" : "employeeManagementIcon-for-light.png";
            setIconImage(new ImageIcon(getClass().getResource("/resources/" + iconName)).getImage());

            prefs.putBoolean("darkMode", isDark);

            UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.PLAIN, 15));
            javax.swing.SwingUtilities.updateComponentTreeUI(this);

            this.revalidate();
            this.repaint();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }

    public void switchPanel(javax.swing.JPanel newPanel, String name) {
        mainPanel.removeAll();
        mainPanel.add(newPanel, name);
        cardLayout.show(mainPanel, name);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void Connect() {
        try {
            connection = DatabaseManager.connectAndInitialize();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database Connecting Failed!\n" + ex.getLocalizedMessage());
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainApp.main(args);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
