
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class UpdatePanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    File selectedFile;
    String fileName, photoPath, newPhotoPath;

    int id;

    /**
     * Creates new form UpdatePanel
     */
    public UpdatePanel(MainFrame mainFrame, int id) {
        this.mainFrame = mainFrame;
        this.id = id;
        initComponents();
        fetch();

        javax.swing.SwingUtilities.invokeLater(() -> fullNameField.requestFocusInWindow());

    }

    private void fetch() {
        try {
            PreparedStatement pstmt = mainFrame.connection.prepareStatement("SELECT * FROM employees_table WHERE employee_id = ?");
            pstmt.setInt(1, id);

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                selectedFile = new File(rs.getString("photo_path"));
                fileName = selectedFile.getName();
                photoPath = selectedFile.getAbsolutePath();

                selectedPhotoLabel.setText("Selected Photo: " + photoPath);
                photoLabel.setIcon(new ImageIcon(new ImageIcon(photoPath).getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                photoLabel.setText("");

                fullNameField.setText(rs.getString("full_name"));
                birthDateField.setText(rs.getString("birth_date"));
                genderComboBox.setSelectedItem(rs.getString("gender"));
                addressField.setText(rs.getString("address"));
                contactNumberField.setText(rs.getString("contact_number"));
                emailField.setText(rs.getString("email_address"));
                positionField.setText(rs.getString("position"));
                departmentField.setText(rs.getString("department"));
                salaryField.setText(rs.getString("salary"));
                hiredDateField.setText(rs.getString("hired_date"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Fetching Failed!\n" + ex.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        updateDetailsLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        selectedPhotoLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        birthDateLabel = new javax.swing.JLabel();
        birthDateField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        contactNumberLabel = new javax.swing.JLabel();
        contactNumberField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        positionField = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        departmentField = new javax.swing.JTextField();
        salaryLabel = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        hiredDateLabel = new javax.swing.JLabel();
        hiredDateField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setAutoscrolls(true);
        setLayout(new java.awt.GridBagLayout());

        updateDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        updateDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateDetailsLabel.setText("Update Details");
        add(updateDetailsLabel, new java.awt.GridBagConstraints());

        photoLabel.setBackground(new java.awt.Color(255, 255, 255));
        photoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        photoLabel.setForeground(new java.awt.Color(0, 0, 0));
        photoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLabel.setText("Select photo");
        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        photoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        photoLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        photoLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        photoLabel.setOpaque(true);
        photoLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        photoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(photoLabel, gridBagConstraints);

        selectedPhotoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectedPhotoLabel.setText("Selected Photo: None");
        selectedPhotoLabel.setMaximumSize(new java.awt.Dimension(500, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(selectedPhotoLabel, gridBagConstraints);

        formPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        formPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        formPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        formPanel.setOpaque(false);
        formPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        formPanel.setLayout(new java.awt.GridBagLayout());

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullNameLabel.setText("Full Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(fullNameLabel, gridBagConstraints);

        fullNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullNameField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        formPanel.add(fullNameField, gridBagConstraints);

        birthDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthDateLabel.setText("Birth Date: (YYYY-MM-DD)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(birthDateLabel, gridBagConstraints);

        birthDateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthDateField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        formPanel.add(birthDateField, gridBagConstraints);

        genderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderLabel.setText("Gender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(genderLabel, gridBagConstraints);

        genderComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        formPanel.add(genderComboBox, gridBagConstraints);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(addressLabel, gridBagConstraints);

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 10);
        formPanel.add(addressField, gridBagConstraints);

        contactNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactNumberLabel.setText("Contact Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(contactNumberLabel, gridBagConstraints);

        contactNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactNumberField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 10);
        formPanel.add(contactNumberField, gridBagConstraints);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(emailLabel, gridBagConstraints);

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        formPanel.add(emailField, gridBagConstraints);

        positionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        positionLabel.setText("Position:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(positionLabel, gridBagConstraints);

        positionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        positionField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        formPanel.add(positionField, gridBagConstraints);

        departmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departmentLabel.setText("Department:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(departmentLabel, gridBagConstraints);

        departmentField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departmentField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        formPanel.add(departmentField, gridBagConstraints);

        salaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salaryLabel.setText("Salary:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(salaryLabel, gridBagConstraints);

        salaryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salaryField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        formPanel.add(salaryField, gridBagConstraints);

        hiredDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hiredDateLabel.setText("Hired Date: (YYYY-MM-DD)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        formPanel.add(hiredDateLabel, gridBagConstraints);

        hiredDateField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hiredDateField.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        formPanel.add(hiredDateField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(formPanel, gridBagConstraints);

        buttonPanel.setMaximumSize(new java.awt.Dimension(230, 50));
        buttonPanel.setMinimumSize(new java.awt.Dimension(230, 50));
        buttonPanel.setOpaque(false);
        buttonPanel.setPreferredSize(new java.awt.Dimension(230, 50));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setFocusable(false);
        updateButton.setMaximumSize(new java.awt.Dimension(105, 40));
        updateButton.setMinimumSize(new java.awt.Dimension(105, 40));
        updateButton.setPreferredSize(new java.awt.Dimension(105, 40));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        buttonPanel.add(updateButton, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setFocusable(false);
        cancelButton.setMaximumSize(new java.awt.Dimension(105, 40));
        cancelButton.setMinimumSize(new java.awt.Dimension(105, 40));
        cancelButton.setPreferredSize(new java.awt.Dimension(105, 40));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        buttonPanel.add(cancelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void photoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoLabelMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Employee Photo");
        int result = chooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = chooser.getSelectedFile();
            fileName = selectedFile.getName();
            newPhotoPath = selectedFile.getPath();

            selectedPhotoLabel.setText("Selected Photo: " + newPhotoPath);
            photoLabel.setIcon(new ImageIcon(new ImageIcon(newPhotoPath).getImage().getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), Image.SCALE_SMOOTH)));
            photoLabel.setText("");
        }
    }//GEN-LAST:event_photoLabelMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String fullName = fullNameField.getText();
            String birthDate = birthDateField.getText();
            String gender = genderComboBox.getSelectedItem().toString();
            String address = addressField.getText();
            String contact = contactNumberField.getText();
            String email = emailField.getText();
            String position = positionField.getText();
            String department = departmentField.getText();
            String salary = salaryField.getText();
            String hiredDate = hiredDateField.getText();

            if (fullName.isEmpty() || address.isEmpty() || contact.isEmpty() || email.isEmpty()
                    || position.isEmpty() || department.isEmpty() || salary.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All Field Must be Field Out!");
            } else {
                if (newPhotoPath != null || photoPath != null) {
                    // Create "photos" folder if it doesn't exist
                    File photoDir = new File("photos");
                    if (!photoDir.exists()) {
                        photoDir.mkdir();
                    }

                    if (newPhotoPath == null) {
                        newPhotoPath = photoPath;
                    }

                    // Copy selected photo to "photos" folder
                    File destinationFile = new File(photoDir, fileName);
                    Files.copy(selectedFile.toPath(), destinationFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

                    // Prepare to insert into database
                    newPhotoPath = destinationFile.getPath();

                    // Insert into database
                    String sql = "UPDATE employees_table SET photo_path = ?, full_name = ?, birth_date = ?, gender = ?, address = ?, "
                            + "contact_number = ?, email_address = ?, position = ?, department = ?, salary = ?, hired_date = ? WHERE employee_id = ?";
                    PreparedStatement pstmt = mainFrame.connection.prepareStatement(sql);

                    pstmt.setString(1, newPhotoPath);
                    pstmt.setString(2, fullName);
                    pstmt.setString(3, birthDate);
                    pstmt.setString(4, gender);
                    pstmt.setString(5, address);
                    pstmt.setString(6, contact);
                    pstmt.setString(7, email);
                    pstmt.setString(8, position);
                    pstmt.setString(9, department);
                    pstmt.setDouble(10, Double.parseDouble(salary));
                    pstmt.setString(11, hiredDate);
                    pstmt.setInt(12, id);

                    pstmt.executeUpdate();

                    mainFrame.add(mainFrame.buttonsPanel, java.awt.BorderLayout.WEST);

                    mainFrame.switchPanel(new ViewEmployeesPanel(mainFrame), "ViewEmployees");

                    JOptionPane.showMessageDialog(this, "Update Successful!");

                } else {
                    JOptionPane.showMessageDialog(this, "No photo selected!");
                }
            }
        } catch (java.lang.NumberFormatException ex) {
            Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please Enter a Number for Salary: " + ex.getMessage());
        } catch (java.io.IOException | java.sql.SQLException ex) {
            Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to Cancel?",
                "Confimation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            mainFrame.add(mainFrame.buttonsPanel, java.awt.BorderLayout.WEST);

            mainFrame.switchPanel(new ViewEmployeesPanel(mainFrame), "ViewEmployees");
        }
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField birthDateField;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField contactNumberField;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JTextField departmentField;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField hiredDateField;
    private javax.swing.JLabel hiredDateLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField positionField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel selectedPhotoLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateDetailsLabel;
    // End of variables declaration//GEN-END:variables
}
