
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class ViewDetailsPanel extends javax.swing.JPanel {

    MainFrame mainFrame;

    int id;

    /**
     * Creates new form UpdatePanel
     */
    public ViewDetailsPanel(MainFrame mainFrame, int id) {
        this.mainFrame = mainFrame;
        this.id = id;
        initComponents();
        fetch();
    }

    private void fetch() {
        mainFrame.Connect();
        try {
            PreparedStatement pstmt = mainFrame.connection.prepareStatement("SELECT * FROM employees_table WHERE employee_id = ?");
            pstmt.setInt(1, id);

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                qrPhotoLabel.setIcon(new ImageIcon(new ImageIcon("qrcodes/" + id + ".png").getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                qrPhotoLabel.setText("");

                File selectedFile = new File(rs.getString("photo_path"));
                String photoPath = selectedFile.getAbsolutePath();

                photoLabel.setIcon(new ImageIcon(new ImageIcon(photoPath).getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                photoLabel.setText("");

                fullNameLabel.setText(rs.getString("full_name"));

                employeeIdLabel.setText("<html><b>EMPLOYEE ID:</b> " + rs.getString("employee_id") + "</html>");
                birthDateLabel.setText("<html><b>BIRTH DATE:</b> " + rs.getString("birth_date") + "</html>");
                genderLabel.setText("<html><b>GENDER:</b> " + rs.getString("gender") + "</html>");
                addressLabel.setText("<html><b>ADDRESS:</b> " + rs.getString("address") + "</html>");
                contactNumberLabel.setText("<html><b>CONTACT NUMBER:</b> " + rs.getString("contact_number") + "</html>");
                emailAddressLabel.setText("<html><b>EMAIL ADDRESS:</b> " + rs.getString("email_address") + "</html>");
                positionLabel.setText("<html><b>POSITION:</b> " + rs.getString("position") + "</html>");
                departmentLabel.setText("<html><b>DEPARTMENT:</b> " + rs.getString("department") + "</html>");
                salaryLabel.setText("<html><b>SALARY:</b> " + rs.getString("salary") + "</html>");
                hiredDateLabel.setText("<html><b>HIRED DATE:</b> " + rs.getString("hired_date") + "</html>");

            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Fetching Failed!\n" + ex.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        allDetailsPanel = new javax.swing.JPanel();
        photoNamePanel = new javax.swing.JPanel();
        qrPhotoLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        moreDetailsPanel = new javax.swing.JPanel();
        employeeIdLabel = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        hiredDateLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 658));
        setPreferredSize(new java.awt.Dimension(600, 658));
        setLayout(new java.awt.GridBagLayout());

        allDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        allDetailsPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        allDetailsPanel.setPreferredSize(new java.awt.Dimension(700, 800));
        allDetailsPanel.setLayout(new java.awt.BorderLayout());

        photoNamePanel.setMaximumSize(new java.awt.Dimension(0, 400));
        photoNamePanel.setMinimumSize(new java.awt.Dimension(0, 220));
        photoNamePanel.setOpaque(false);
        photoNamePanel.setPreferredSize(new java.awt.Dimension(0, 280));
        photoNamePanel.setLayout(new java.awt.GridBagLayout());

        qrPhotoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qrPhotoLabel.setForeground(new java.awt.Color(0, 0, 0));
        qrPhotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qrPhotoLabel.setText("QR");
        qrPhotoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        qrPhotoLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        qrPhotoLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        qrPhotoLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        photoNamePanel.add(qrPhotoLabel, gridBagConstraints);

        photoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        photoLabel.setForeground(new java.awt.Color(0, 0, 0));
        photoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLabel.setText("PHOTO");
        photoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        photoLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        photoLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        photoLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        photoNamePanel.add(photoLabel, gridBagConstraints);

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fullNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        fullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameLabel.setText("FULL NAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        photoNamePanel.add(fullNameLabel, gridBagConstraints);

        allDetailsPanel.add(photoNamePanel, java.awt.BorderLayout.NORTH);

        jPanel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        allDetailsPanel.add(jPanel1, java.awt.BorderLayout.WEST);

        moreDetailsPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        moreDetailsPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        moreDetailsPanel.setOpaque(false);
        moreDetailsPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        moreDetailsPanel.setLayout(new java.awt.GridLayout(10, 1));

        employeeIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdLabel.setText("EMPLOYEE ID:");
        moreDetailsPanel.add(employeeIdLabel);

        birthDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        birthDateLabel.setText("BIRTH DATE:");
        moreDetailsPanel.add(birthDateLabel);

        genderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderLabel.setText("GENDER:");
        moreDetailsPanel.add(genderLabel);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(0, 0, 0));
        addressLabel.setText("ADDRESS:");
        moreDetailsPanel.add(addressLabel);

        contactNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        contactNumberLabel.setText("CONTACT NUMBER:");
        moreDetailsPanel.add(contactNumberLabel);

        emailAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailAddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailAddressLabel.setText("EMAIL ADDRESS:");
        moreDetailsPanel.add(emailAddressLabel);

        positionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(0, 0, 0));
        positionLabel.setText("POSITION:");
        moreDetailsPanel.add(positionLabel);

        departmentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        departmentLabel.setForeground(new java.awt.Color(0, 0, 0));
        departmentLabel.setText("DEPARTMENT:");
        moreDetailsPanel.add(departmentLabel);

        salaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(0, 0, 0));
        salaryLabel.setText("SALARY:");
        moreDetailsPanel.add(salaryLabel);

        hiredDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hiredDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        hiredDateLabel.setText("HIRED DATE:");
        moreDetailsPanel.add(hiredDateLabel);

        allDetailsPanel.add(moreDetailsPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        allDetailsPanel.add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        allDetailsPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(allDetailsPanel, new java.awt.GridBagConstraints());

        buttonsPanel.setMaximumSize(new java.awt.Dimension(220, 40));
        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setFocusable(false);
        backButton.setMaximumSize(new java.awt.Dimension(100, 40));
        backButton.setMinimumSize(new java.awt.Dimension(100, 40));
        backButton.setPreferredSize(new java.awt.Dimension(100, 40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        buttonsPanel.add(backButton, gridBagConstraints);

        printButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        printButton.setText("PRINT");
        printButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printButton.setFocusable(false);
        printButton.setMaximumSize(new java.awt.Dimension(100, 40));
        printButton.setMinimumSize(new java.awt.Dimension(100, 40));
        printButton.setPreferredSize(new java.awt.Dimension(100, 40));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        buttonsPanel.add(printButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(buttonsPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainFrame.add(mainFrame.buttonsPanel, java.awt.BorderLayout.WEST);
        mainFrame.switchPanel(new ViewEmployeesPanel(mainFrame), "ViewEmployees");
    }//GEN-LAST:event_backButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print");

        job.setPrintable((graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            // Convert Graphics to Graphics2D
            Graphics2D g2 = (Graphics2D) graphics;
            g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            allDetailsPanel.printAll(g2);
            return Printable.PAGE_EXISTS;
        });

        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
                JOptionPane.showMessageDialog(this, "Printing Done!");
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(this, "Printing Failed!\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel allDetailsPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hiredDateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel moreDetailsPanel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel photoNamePanel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel qrPhotoLabel;
    private javax.swing.JLabel salaryLabel;
    // End of variables declaration//GEN-END:variables
}
